# Generated by Django 5.2.3 on 2025-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['page_index', 'created_at']},
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='page_number',
            new_name='page_index',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_type',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='width',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='y',
        ),
        migrations.AddField(
            model_name='annotation',
            name='highlight_areas',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='quote',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
